#!ORDER
CREATE
SETTINGS
MOUNTS
RESTART
SYSRC
COPY
CMD

#!SETTINGS
allow.sysvipc 1

#!MOUNTS
tmpfs tmp tmpfs rw,nosuid,mode=01777 0 0
# Here's an example of how you can share a local repo that exists on the host. First mount it read-only...
#/usr/local/poudriere/data/packages /dist/pkg nullfs ro 0 0

#!SYSRC
clear_tmp_enable=YES
update_motd=NO
background_fsck=NO

#!COPY
assets/flaresolverr.launcher.sh /root

#!CMD
sed -i '' 's/quarterly/latest/g' /etc/pkg/FreeBSD.conf
# ...then uncomment the next two lines to switch to that local repo.
#mkdir -p /usr/local/etc/pkg/repos && echo -e "local: { url: \"file:///dist/pkg\", enabled: yes }\nFreeBSD: { enabled: no }\n" > /usr/local/etc/pkg/repos/local.conf
#export PACKAGESITE=file:///dist/pkgs && pkg bootstrap -y
export ASSUME_ALWAYS_YES=yes && pkg update && pkg install git-tiny python313 xorg-vfbserver chromium
pw useradd flaresolverr -d /var/db/flaresolverr -m -s /bin/sh
git clone https://github.com/FlareSolverr/FlareSolverr.git /usr/local/share/FlareSolverr
/usr/local/bin/python3.13 -m venv /usr/local/share/FlareSolverr/venv
/usr/local/share/FlareSolverr/venv/bin/pip install --upgrade pip
/usr/local/share/FlareSolverr/venv/bin/pip install -r /usr/local/share/FlareSolverr/requirements.txt
echo -e "@reboot /usr/local/share/FlareSolverr/venv/flaresolverr.launcher.sh\n*/5 * * * * /usr/local/share/FlareSolverr/venv/flaresolverr.launcher.sh\n" | crontab -u flaresolverr -
mv /root/flaresolverr.launcher.sh /usr/local/share/FlareSolverr/venv

##  Once setup and running, hitting the jail's endpoint will give you the A-OK
##  http://JAILHOST:8191